<?php

namespace Proxies\__CG__\CT\VideoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Video extends \CT\VideoBundle\Entity\Video implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'id', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'user', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'videoName', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'videoExt', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'videoPath', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'videoIdbm', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'dataJson', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'castJson', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'video', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'tempVideoname');
        }

        return array('__isInitialized__', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'id', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'user', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'videoName', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'videoExt', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'videoPath', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'videoIdbm', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'dataJson', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'castJson', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'video', '' . "\0" . 'CT\\VideoBundle\\Entity\\Video' . "\0" . 'tempVideoname');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Video $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideoName($videoName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideoName', array($videoName));

        return parent::setVideoName($videoName);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideoName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideoName', array());

        return parent::getVideoName();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideoExt($videoExt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideoExt', array($videoExt));

        return parent::setVideoExt($videoExt);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideoExt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideoExt', array());

        return parent::getVideoExt();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideoPath($videoPath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideoPath', array($videoPath));

        return parent::setVideoPath($videoPath);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideoPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideoPath', array());

        return parent::getVideoPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo(\Symfony\Component\HttpFoundation\File\UploadedFile $video = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', array($video));

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', array());

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function preRemoveUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preRemoveUpload', array());

        return parent::preRemoveUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array());

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', array());

        return parent::getUploadDir();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadRootDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadRootDir', array());

        return parent::getUploadRootDir();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideoIdbm($videoIdbm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideoIdbm', array($videoIdbm));

        return parent::setVideoIdbm($videoIdbm);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideoIdbm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideoIdbm', array());

        return parent::getVideoIdbm();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\CT\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataJson($dataJson)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataJson', array($dataJson));

        return parent::setDataJson($dataJson);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataJson', array());

        return parent::getDataJson();
    }

    /**
     * {@inheritDoc}
     */
    public function setCastJson($castJson)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCastJson', array($castJson));

        return parent::setCastJson($castJson);
    }

    /**
     * {@inheritDoc}
     */
    public function getCastJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCastJson', array());

        return parent::getCastJson();
    }

}
